from __future__ import annotations
import os
import re
from pathlib import Path
from anthropic import Anthropic
from agents.models import BookParams, Outline
from agents.planner import generate_outline
from agents.writer import write_chapter
from research.perplexity import research_topic
from images.generator import generate_images_for_chapter
from export.template_reader import load_template_styles
from export.docx_builder import DocxBuilder


def _sanitize_filename(title: str) -> str:
    return re.sub(r"[^\w\s-]", "", title).strip().replace(" ", "-").lower()


def run(params: BookParams) -> Path:
    """Execute all 5 pipeline phases and return path to the generated .docx."""
    anthropic_key = os.environ["ANTHROPIC_API_KEY"]
    openai_key = os.environ["OPENAI_API_KEY"]
    perplexity_key = os.environ["PERPLEXITY_API_KEY"]
    template_path = os.environ.get(
        "KINDLE_TEMPLATE_PATH", str(Path.home() / "Desktop" / "5 x 8 in.docx")
    )

    # Phase 1 — Research
    print("\n[1/5] 🔍 Researching topic with Perplexity...")
    research = research_topic(params.theme, api_key=perplexity_key)
    print(f"  ✅ Research complete ({len(research)} chars)")

    # Phase 2 — Outline
    print("\n[2/5] 🧠 Generating outline with Opus...")
    outline: Outline = generate_outline(params, research, api_key=anthropic_key)

    # Phase 3 + 4 — Write + generate images per chapter
    chapter_texts: dict[int, str] = {}
    chapter_images: dict[int, list] = {}
    total = len(outline.chapters)

    debug_dir = Path.cwd() / "debug"
    debug_dir.mkdir(exist_ok=True)

    for i, chapter in enumerate(outline.chapters, 1):
        print(f"\n[3/5] ✍️  Writing chapter {i}/{total}...")
        text = write_chapter(chapter, outline, research, api_key=anthropic_key)
        # Save raw writer output for debugging
        (debug_dir / f"chapter_{chapter.number:02d}_raw.txt").write_text(text, encoding="utf-8")
        chapter_texts[chapter.number] = text

        print(f"\n[4/5] 🎨 Generating images for chapter {i}/{total}...")
        images = generate_images_for_chapter(text, api_key=openai_key)
        chapter_images[chapter.number] = images

    # About the author (brief, generated by Haiku)
    client = Anthropic(api_key=anthropic_key)
    print("\n  ✍️  Writing 'About the Author' section...")
    about_resp = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=300,
        messages=[{
            "role": "user",
            "content": (
                f"Write a short 'About the Author' bio (2-3 sentences) for "
                f"{outline.author}, author of '{outline.book_title}'. "
                f"Write in {outline.language}. Professional and engaging."
            ),
        }],
    )
    about_author = about_resp.content[0].text

    # Phase 5 — Export
    print("\n[5/5] 📄 Assembling .docx...")
    styles = load_template_styles(template_path)
    builder = DocxBuilder(styles=styles)
    docx_bytes = builder.build(
        outline=outline,
        chapter_texts=chapter_texts,
        chapter_images=chapter_images,
        about_author=about_author,
    )

    filename = f"{_sanitize_filename(outline.book_title)}.docx"
    output_path = Path.cwd() / filename
    output_path.write_bytes(docx_bytes)

    print(f"\n✅ Book saved: {output_path}")
    return output_path
